blog/urls.py
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


# Create your models here.

STATUS = (
    (0,"Rascunho"),
    (1,"Publicado")
)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name='blog_posts')
    title = models.CharField(max_length= 75, verbose_name="Título")
    byline = models.CharField(max_length=275, verbose_name="Subtítulo")
    text = models.TextField(verbose_name="Corpo")
    image = models.ImageField(upload_to='post', blank= True, null=True, verbose_name="Imagem")
    slug = models.SlugField(max_length=128, verbose_name="URL")
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return "%s" % (self.title)

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post

# Create your views here.

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

blog/templates/base.html
{% load static %}

<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" type="image/png" href="{% static 'blog/assets/img/favicon.png' %}">
  <title>João de Sousa - {% block title %} {% endblock %}</title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="{% static 'blog/assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'blog/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <link href="{% static 'blog/assets/css/font-awesome.css' %}" rel="stylesheet" />
  <link href="{% static 'blog/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static 'blog/assets/css/argon-design-system.css' %}" rel="stylesheet" />
  <!-- OpenGraph -->
  <meta property="og:title"              content="João de Sousa" />
  <meta property="og:description"        content="Estava tudo à espera de uma coisa em condições." />
  <meta property="og:image"              content="{% static 'blog/assets/img/featured.png' %}" />
</head>

<body class="sections-page">
      <header class="header-2 skew-separator">
        <nav class="navbar navbar-expand-lg navbar-dark navbar-absolute">
          <div class="container">
            <div class="navbar-translate">
              <a class="navbar-brand" href="{% url 'home' %}">João de Sousa</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#example-header-2" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="example-header-2">
              <div class="navbar-collapse-header">
                <div class="row">
                  <div class="col-6 collapse-brand">
                    <a>
                      
                    </a>
                  </div>
                  <div class="col-6 collapse-close text-right">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#example-header-2" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                      <span></span>
                      <span></span>
                    </button>
                  </div>
                </div>
              </div>
              <ul class="nav navbar-nav ml-lg-auto">
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://twitter.com/ojoaodesousa">
                    <i class="fab fa-twitter"></i>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://www.facebook.com/ojoaodesousa">
                    <i class="fab fa-facebook-square"></i>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://www.instagram.com/ojoaodesousa">
                    <i class="fab fa-instagram"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div class="page-header" style="min-height: 45vh;">
          <div class="page-header-image" style="background-image: url('{% static 'blog/assets/img/home.jpg' %}'); opacity: 0.85;"></div>
          <div class="container">
            <div class="row">
              <div class="col-md-8 mx-auto text-center">
                <img src="{% static 'blog/assets/img/logo_w.png' %}" width="40%">
              </div>
            </div>
          </div>
        </div>
      </header>

  {% block content%}
  {% endblock %}




<footer class="footer bg-white footer-simple">
            <div class="container">
              <div class="copyright">
                <p>Made with a ⌨️ and ☕ by <a href="https://joaodesousa.com">João de Sousa</a>.
              </div>
            </div>
          </footer>
  {% block js %}
  <!-- Scripts -->

  <!-- Core -->
  <script src="{% static 'blog/assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'blog/assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'blog/assets/js/core/bootstrap.min.js' %}"></script>
  {% endblock %}



</body>

</html>

blog/templates/base_detail.html
{% load static %}

<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" type="image/png" href="{% static 'blog/assets/img/favicon.png' %}">
  <title>João de Sousa - {% block title %} {% endblock %}</title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />

  <!-- Nucleo Icons -->
  <link href="{% static 'blog/assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'blog/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <link href="{% static 'blog/assets/css/font-awesome.css' %}" rel="stylesheet" />
  <link href="{% static 'blog/assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static 'blog/assets/css/argon-design-system.css' %}" rel="stylesheet" />
  <!-- OpenGraph -->
  {% block opengraph %}{% endblock opengraph%}
</head>

<body class="sections-page">
      <header class="header-2 skew-separator">
        <nav class="navbar navbar-expand-lg navbar-dark navbar-absolute">
          <div class="container">
            <div class="navbar-translate">
              <a class="navbar-brand" href="{% url 'home' %}">João de Sousa</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#example-header-2" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="example-header-2">
              <div class="navbar-collapse-header">
                <div class="row">
                  <div class="col-6 collapse-brand">
                    <a>
                      
                    </a>
                  </div>
                  <div class="col-6 collapse-close text-right">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#example-header-2" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                      <span></span>
                      <span></span>
                    </button>
                  </div>
                </div>
              </div>
              <ul class="nav navbar-nav ml-lg-auto">
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://twitter.com/ojoaodesousa">
                    <i class="fab fa-twitter"></i>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://www.facebook.com/ojoaodesousa">
                    <i class="fab fa-facebook-square"></i>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://www.instagram.com/ojoaodesousa">
                    <i class="fab fa-instagram"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div class="page-header" style="min-height: 45vh;">
          <div class="page-header-image" style="background-image: url('{{post.image.url}}'); opacity: 0.85;"></div>
          <div class="container">
            <div class="row">
              <div class="col-md-8 mx-auto text-center">
                <img src="{% static 'blog/assets/img/logo_w.png' %}" width="40%">
              </div>
            </div>
          </div>
        </div>
      </header>

  {% block content%}
  {% endblock %}



<footer class="footer bg-white footer-simple">
            <div class="container">
              <div class="copyright">
                <p>Made with a ⌨️ and ☕ by <a href="https://joaodesousa.com">João de Sousa</a>.
              </div>
            </div>
          </footer>
  {% block js %}
  <!-- Scripts -->

  <!-- Core -->
  <script src="{% static 'blog/assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'blog/assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'blog/assets/js/core/bootstrap.min.js' %}"></script>
  {% endblock %}



</body>

</html>

blog/templates/index.html
{% extends "base.html" %}
{% block title %}Blog{% endblock title %}
{% block content %}


<section class="blogs-2">
    <div class="container-fluid">

        <div class="row">
            {% for post in post_list %}
            {% if forloop.counter == 1 %}
            <div class="col-lg-10 mx-auto">
                <div class="card card-blog card-background">
                    <div class="full-background" style="background-image: url('{{post.image.url}}"></div>
                    <a href="{% url 'post_detail' post.slug  %}">
                        <div class="card-body">
                            <div class="content-bottom">
                                <h6 class="card-category text-white opacity-8">{{post.created_on|date:"d F, Y"}}</h6>
                                <h5 class="card-title">{{post.title}}</h5>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            {% else %}
            <div class="col-lg-5">
                <div class="card card-blog card-background">
                    <div class="full-background" style="background-image: url('{{post.image.url}}')"></div>
                    <a href="{% url 'post_detail' post.slug  %}">
                        <div class="card-body">
                            <div class="content-bottom">
                                <h6 class="card-category text-white opacity-8">{{post.created_on}}</h6>
                                <h5 class="card-title">{{post.title}}</h5>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>
{%endblock%}

blog/templates/post_detail.html
  {% extends "base_detail.html" %}
  {% block title %}Blog{% endblock title %}
  {% block opengraph %}
  <meta property="og:title"              content="{{post.title}}" />
  <meta property="og:description"        content="{{post.byline}}" />
  <meta property="og:image"              content="{{post.image.url}}" />
  {% endblock opengraph%}
  {% block content %}
  {% load static %}

  <div class="wrapper">
    <section class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-10 ml-auto mr-auto">
            <h6 class="category">{{post.created_on}}</h6>
            <h2 class="display-3">{{post.title}}</h2>
            <p class="lead text-muted"><small>{{post.byline}}</small></p>
          </div>
        </div>
            <div class="row align-items-center mt--3">
              <div class="col-md-3 text-lg-right">
                <!-- Avatar -->
                  <img src="{% static 'blog/assets/img/1448278.jpg' %}" style="filter: grayscale(100%); -webkit-filter: grayscale(100%);" width="60%">
              </div>
              <div class="col-md-9 mt-6">
                <h3 class="heading">João de Sousa</h3>
                <p class="text-muted">Presidente da Associação Juvenil de Lousada e Vice-Presidente da Federação Nacional dos <br>Estudos Europeus</p>
              </div>
            </div>
            <div class="border-bottom mb-3 ml-6 mr-6"></div>
        <div class="row">
          <div class="col-md-12 ml-auto mr-auto">
            {{post.text|safe}}
          </div>
          </div>
    </section>
  </div>
  {%endblock%}